In [1]:
import numpy as np

In [2]:
arr1D = np.array([1, 2, 3, 4, 5])
arr2D = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

def fun():

  print(f"1D Array: {arr1D}")
  print(f"2D Array:\n{arr2D}")


  print(f"\nSum of 1D array:\n{arr1D} is: {np.sum(arr1D)}")
  print(f"\nSum of 2D array:\n{arr2D} is: {np.sum(arr2D)}")
  print(f"\nTranspose of 2D array:\n{arr2D}\n\nis:\n{arr2D.T}")

fun()

1D Array: [1 2 3 4 5]
2D Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

Sum of 1D array:
[1 2 3 4 5] is: 15

Sum of 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]] is: 45

Transpose of 2D array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]

is:
[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [3]:
def rand():
  image = np.random.randint(0, 256, (5, 5), dtype = np.uint8)
  print(f"Original image:\n {image}")


  cropped = image[1:4, 1:4]
  print(f"\nCropped section:\n {cropped}")


  inverted = 255 - image
  print(f"\nInverted image:\n {inverted}")


rand()

Original image:
 [[ 10 106 212 167 247]
 [ 75 103 163  78 128]
 [ 50  52  10 238 247]
 [135 243 163 245 196]
 [ 17 147 212 173  54]]

Cropped section:
 [[103 163  78]
 [ 52  10 238]
 [243 163 245]]

Inverted image:
 [[245 149  43  88   8]
 [180 152  92 177 127]
 [205 203 245  17   8]
 [120  12  92  10  59]
 [238 108  43  82 201]]


In [5]:
import cv2
from google.colab.patches import cv2_imshow

In [7]:
from google.colab import drive
drive.mount('/content/drive')

MessageError: Error: credential propagation was unsuccessful