In [1]:
# Assigning functions to variables

def say_something():
  print("This is me saying something")



saying = say_something

saying()

This is me saying something


In [2]:
# Passing functions as arguments

def add(a, b):
  return a + b

def sub(a, b):
  return a - b

def mult(a, b):
  return a * b

def div(a, b):
  return a / b


def opNumber(f, a, b):
  return f(a, b)



print(f"The sum of 2 and 3 is: {opNumber(add, 2, 3)}")
print(f"The difference of 2 and 3 is: {opNumber(sub, 2, 3)}")
print(f"The product of 2 and 3 is: {opNumber(mult, 2, 3)}")
print(f"The quotient of 2 and 3 is: {opNumber(div, 2, 3)}")

The sum of 2 and 3 is: 5
The difference of 2 and 3 is: -1
The product of 2 and 3 is: 6
The quotient of 2 and 3 is: 0.6666666666666666


In [3]:
# Returning functions from other functions

def adder(num1):
  def adding(num2):
    return num1 + num2
  return adding



startingAdd = adder(4)
print(startingAdd(6))

10


In [4]:
# Recursive function

def factorial(n):
  if n == 1:
    return 1
  return n * factorial(n - 1)



print(factorial(5))

120


In [5]:
# Doc strings

def add(a, b):
  '''Adds both the numbers passed as parameters'''
  return a + b


help(add)

Help on function add in module __main__:

add(a, b)
    Adds both the numbers passed as parameters



In [6]:
# Local variables

def add():
  a = 1
  b = 1
  print(f"The sum of {a} and {b} is: {a + b}")



add()

The sum of 1 and 1 is: 2


In [7]:
# Global variables

a = 2
b = 2

def add():
  print(f"The sum of {a} and {b} is: {a + b}")



add()

The sum of 2 and 2 is: 4


In [8]:
a = 10
b = 20

def add():
  global b
  b = 10
  print(f"The sum of {a} and {b} is: {a + b}")



add()

The sum of 10 and 10 is: 20


In [9]:
def bigboy():
  a = 6
  def lilboy():
    nonlocal a
    a =5
  lilboy()
  print(f"The value of x in the bigboy league is: {a}")

bigboy()

The value of x in the bigboy league is: 5


In [14]:
import numpy as np

In [13]:
# Python lists and NumPy arrays
import numpy as np
za_py_list = [1, 2, 3, 4, 5]
za_np_array = np.array([1, 2, 3, 4, 5])

print(type(za_py_list))
print(type(za_np_array))

<class 'list'>
<class 'numpy.ndarray'>


In [15]:
# Dimensional arrays

array_1D = np.array([1, 2, 3, 4, 5])
print(array_1D)

array_2D = np.array([[1, 2, 3],
                    [4, 5, 6]])
print(array_2D)

print(array_2D.ndim)

[1 2 3 4 5]
[[1 2 3]
 [4 5 6]]
2


In [16]:
# Array of zeroes

zeros_array = np.zeros((2, 3))
print(zeros_array)


# Array of ones

ones_array = np.ones((2, 3))
print(ones_array)


# Array of nines

nines_array = np.full((2, 3), 9)
print(nines_array)

[[0. 0. 0.]
 [0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]]
[[9 9 9]
 [9 9 9]]


In [17]:
# Numpy array of evenly spaced values

linspace_array = np.linspace(1, 21, 4)
print(linspace_array)


# Numpy array with number range

range_array = np.arange(1, 21, 4)
print(range_array)

[ 1.          7.66666667 14.33333333 21.        ]
[ 1  5  9 13 17]


In [18]:
# Random numpy array between 0 & 1

ran_array = np.random.rand(3, 3)
print(ran_array)


# Random array between 1 & 499

ran2_arr = np.random.randint(1, 500, (3, 3))
print(ran2_arr)
print(ran2_arr.ndim)

[[0.20038649 0.75166187 0.87534584]
 [0.95736258 0.37506037 0.57155258]
 [0.7016258  0.12197687 0.58162285]]
[[ 31 120  18]
 [459 425  97]
 [238 291 121]]
2


In [19]:
# Shape, size and dimensions of array

arr3 = np.array([[1, 2, 3],
                 [4, 5, 6]])

print(arr3.shape)
print(arr3.size)
print(arr3.ndim)

(2, 3)
6
2


In [20]:
# Reshaping arrays

og_array = np.array([9, 8, 7, 6, 5, 4])
print(og_array)

reshaped_array = og_array.reshape(2, 3)
print(reshaped_array)

[9 8 7 6 5 4]
[[9 8 7]
 [6 5 4]]


In [21]:
arr1 = np.array([1, 2, 3])
arr2 = np.array([4, 5, 6])

print(f"The sum of {arr1} and {arr2} is: {arr1 + arr2}")

The sum of [1 2 3] and [4 5 6] is: [5 7 9]


In [22]:
# min, max, sum

arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(np.max(arr))
print(np.min(arr))
print(np.sum(arr))

6
1
21


In [23]:
# Array indexing

arr = np.array([[1, 2, 3],
                [4, 5, 6],
                [7, 8, 9]])

i = 2
j = 2

print(f"A random number at index: ({i}, {j}) is {arr[i, j]}")

A random number at index: (2, 2) is 9


In [24]:
# Slicing concept

arr1 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
print(arr1[::-1])


arr2 = np.array([[9, 8, 7],
                 [6, 5, 4],
                 [3, 2, 1]])
print(arr2[:-1:])

[1 2 3 4 5 6 7 8 9]
[[9 8 7]
 [6 5 4]]


In [25]:
# Conditional filtering

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9])
gibeth = np.where(arr > 7)

print(gibeth)

(array([7, 8]),)


In [26]:
arr1 = np.array([9, 8, 7, 6, 5, 4, 3, 2, 1])
print(arr1)

arr2 = np.take(arr1, [0, 4, 6, 7])
print(arr2)

np.put(arr1, [0, 4, 6, 7], [5, 1, 8, 7])
print(arr1)

[9 8 7 6 5 4 3 2 1]
[9 5 3 2]
[5 8 7 6 1 4 8 7 1]
